import React from "react";

const Data2 = () => {
  const data = [
    { game: "ludo", name: "kunal", entry: "500/-" },
    { game: "ludo", name: "Raghavendra", entry: "500/-" },
    { game: "ludo", name: "Ashwini", entry: "500/-" },
    { game: "ludo", name: "Siddharth", entry: "500/-" },
    { game: "ludo", name: "Anjali", entry: "500/-" },
    { game: "ludo", name: "Vikram", entry: "500/-" },
    { game: "ludo", name: "Meera", entry: "500/-" },
    { game: "ludo", name: "Rohan", entry: "500/-" },
    { game: "ludo", name: "Aditi", entry: "500/-" },
    { game: "ludo", name: "Harsh", entry: "500/-" },
    { game: "ludo", name: "Sana", entry: "500/-" },
    { game: "ludo", name: "Karan", entry: "500/-" },
    { game: "ludo", name: "Priya", entry: "500/-" },
    { game: "ludo", name: "Rajat", entry: "500/-" },
    { game: "ludo", name: "Nisha", entry: "500/-" },
    { game: "ludo", name: "Amit", entry: "500/-" },
    { game: "ludo", name: "Sneha", entry: "500/-" },
    { game: "ludo", name: "Raj", entry: "500/-" },
    { game: "ludo", name: "Tanvi", entry: "500/-" },
    { game: "ludo", name: "Nitin", entry: "500/-" },
    { game: "ludo", name: "Isha", entry: "500/-" },
    { game: "ludo", name: "Mohan", entry: "500/-" },
    { game: "ludo", name: "Pooja", entry: "500/-" },
    { game: "ludo", name: "Ankit", entry: "500/-" },
    { game: "ludo", name: "Neha", entry: "500/-" },
    { game: "ludo", name: "Manish", entry: "500/-" },
    { game: "ludo", name: "Simran", entry: "500/-" },
    { game: "ludo", name: "Ravi", entry: "500/-" },
    { game: "ludo", name: "Bhavna", entry: "500/-" },
    { game: "ludo", name: "Vivek", entry: "500/-" },
    { game: "ludo", name: "Geeta", entry: "500/-" },
    { game: "ludo", name: "Sunil", entry: "500/-" },
    { game: "ludo", name: "Ritu", entry: "500/-" },
    { game: "ludo", name: "Kunal", entry: "500/-" },
    { game: "ludo", name: "Arti", entry: "500/-" },
    { game: "ludo", name: "Abhishek", entry: "500/-" },
    { game: "ludo", name: "Sonal", entry: "500/-" },
    { game: "ludo", name: "Gaurav", entry: "500/-" },
    { game: "ludo", name: "Neetu", entry: "500/-" },
    { game: "ludo", name: "Suresh", entry: "500/-" },
    { game: "ludo", name: "Kiran", entry: "500/-" },
    { game: "ludo", name: "Vikas", entry: "500/-" },
    { game: "ludo", name: "Pallavi", entry: "500/-" },
    { game: "ludo", name: "Rahul", entry: "500/-" },
    { game: "ludo", name: "Komal", entry: "500/-" },
    { game: "ludo", name: "Ajay", entry: "500/-" },
    { game: "ludo", name: "Madhuri", entry: "500/-" },
    { game: "ludo", name: "Sahil", entry: "500/-" },
    { game: "ludo", name: "Nidhi", entry: "500/-" },
  ];

  return data;
};

export default Data2;
